# Generated by Django 4.2.5 on 2023-09-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='productos',
            new_name='productos_categoria',
        ),
    ]
