# Generated by Django 4.2 on 2023-10-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_producto_categorias_producto_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='name',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='ventas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_final',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='product',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre de la categoria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_vendido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto', verbose_name='Producto vendido'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='productos_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto', verbose_name='Categoria del producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta', verbose_name='Producto comprado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.PositiveIntegerField(verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
