# Generated by Django 4.2.6 on 2024-07-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='is_activate',
            field=models.BooleanField(verbose_name='¿Esta activo?'),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='is_activate',
            field=models.BooleanField(verbose_name='¿Esta activo?'),
        ),
    ]
