# Generated by Django 5.2.3 on 2025-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_designer_is_activate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_disenador",
                    models.CharField(
                        max_length=100, verbose_name="Nombres y apellidos"
                    ),
                ),
                (
                    "nombre_usuario",
                    models.CharField(max_length=50, verbose_name="Nombre de usuario"),
                ),
                ("edad", models.PositiveSmallIntegerField(verbose_name="Edad")),
                ("esta_activo", models.BooleanField(verbose_name="¿Esta activo?")),
            ],
            options={
                "verbose_name": "Diseñador",
                "verbose_name_plural": "Diseñadores",
            },
        ),
        migrations.CreateModel(
            name="Programador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_programador",
                    models.CharField(
                        max_length=100, verbose_name="Nombres y apellidos"
                    ),
                ),
                (
                    "nombre_usuario",
                    models.CharField(max_length=50, verbose_name="Nombre de usuario"),
                ),
                ("edad", models.PositiveSmallIntegerField(verbose_name="Edad")),
                ("esta_activo", models.BooleanField(verbose_name="¿Esta activo?")),
            ],
            options={
                "verbose_name": "Programador",
                "verbose_name_plural": "Programadores",
            },
        ),
        migrations.DeleteModel(
            name="Designer",
        ),
        migrations.DeleteModel(
            name="Programmer",
        ),
    ]
