# Generated by Django 4.2.6 on 2025-07-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_categoria",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Nombre de la categoria"
                    ),
                ),
                ("descripcion_categoria", models.TextField(verbose_name="Descripcion")),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_producto",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Nombre del producto"
                    ),
                ),
                (
                    "precio_producto",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, null=True, verbose_name="Precio"
                    ),
                ),
                (
                    "cantidad_producto",
                    models.PositiveIntegerField(verbose_name="Cantidad"),
                ),
                (
                    "categoria_producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.categoria",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_proveedor",
                    models.CharField(
                        max_length=200, verbose_name="Nombres y apellidos"
                    ),
                ),
                (
                    "numero_telefono",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número de telefono"
                    ),
                ),
                (
                    "numero_ruc",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="RUC"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descuento_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.0",
                        max_digits=3,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(auto_now=True, verbose_name="Fecha de venta"),
                ),
                (
                    "producto_vendido",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                        verbose_name="Producto vendido",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor_producto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.proveedor",
                verbose_name="Proveedor",
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos_cliente",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Nombres y apellidos"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("EXTRANJERIA", "Carnet de Extranjeria"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_identidad",
                    models.PositiveIntegerField(verbose_name="Numero de identidad"),
                ),
                (
                    "compra_cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.venta",
                        verbose_name="Producto comprado",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
